from .auth_routes import auth_bp
from .dashboard_routes import dashboard_bp
from .household_routes import household_bp
from .encounter_routes import encounter_bp
from .output_routes import output_bp
from .followup_routes import followup_bp
from .analytics_routes import analytics_bp
from .sync_routes import sync_bp
from .demo_routes import demo_bp
from .admin_routes import admin_bp
from .retrieval_routes import retrieval_bp
